"""Add avatar field to User model

Revision ID: 21503937f11c
Revises: 9b10f5634c43
Create Date: 2024-05-15 18:23:27.363497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21503937f11c'
down_revision = '9b10f5634c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
