"""Add created_at field to User model

Revision ID: 4dbbaca647ea
Revises: 
Create Date: 2024-05-15 15:42:28.643155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dbbaca647ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('drink_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('drink_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
