"""Temporary change to force migration

Revision ID: 9ec24f93d444
Revises: 4dbbaca647ea
Create Date: 2024-05-15 16:26:00.401085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec24f93d444'
down_revision = '4dbbaca647ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('temp_field', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('temp_field')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
